name: perfTest1
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: dis <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter
- $dart2js:
    checked: false
    minify: true
    sourceMaps: true
    suppressWarnings: false
    suppressHints: false
    csp: false
    commandLineOptions:
    - --trust-primitives
    - --trust-type-annotations